services:
  db:
    image: postgres:16-alpine
    container_name: catalogo_db
    environment:
      POSTGRES_DB: catalogo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
     - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: